table Exame
	lineageTag: a2b1c398-5a81-4d9f-9269-0969207b636a

	measure Exame = COUNTROWS(fato_exame)
		formatString: #,0
		lineageTag: 0243a36a-b5a8-4d7c-9111-5314d6eea962

	partition Exame = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

