table SLA
	lineageTag: 2366820c-bfe4-4fd7-a623-f6eb387a2a00

	measure 'SLA Cumprido %' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS(fato_exame), fato_exame[sla_cumprido] = TRUE()),
			    COUNTROWS(fato_exame),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 569ffe74-88be-48ea-9141-3285a166b1ab

	measure 'SLA Cumprido Ano Anterior %' =
			
			CALCULATE(SLA[SLA Cumprido %], SAMEPERIODLASTYEAR(dim_tempo[data]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f8b52bc7-5c80-4c03-af8b-38c3abd5727d

	measure 'SLA Cumprido variacao ano %' =
			
			DIVIDE(
			        ([SLA Cumprido %] - [SLA Cumprido Ano Anterior %]),
			        [SLA Cumprido Ano Anterior %],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5ee04263-4e9f-4315-8d07-a5cab244833e

	measure 'SLA Cumprido dinamico variacao' = ```
			
			VAR VOL = DIVIDE(
			        ([SLA Cumprido %]-[SLA Cumprido Ano Anterior %]), [SLA Cumprido Ano Anterior %],0)
			
			VAR ICON = 
			        SWITCH(
			        TRUE(),
			            [SLA Cumprido variacao ano %] >0,"⮝ ",
			            [SLA Cumprido variacao ano %] <0,"⮟"
			        )
			        VAR 
			            RESULT = 
			                    IF(VOL = 0 , BLANK() , 
			                    CONCATENATE(ICON,CONCATENATE("",FORMAT(VOL,"0.00%;-0.00%;0.00%")))&" vs ano anterior")
			RETURN
			RESULT
			```
		lineageTag: a82ba70b-1db2-4c74-bbbd-1f3aacd2adbb

	partition SLA = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

